### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by SOF3** [ifvictr/sofeme#1]
This website is not unique enough. It only contains the conventional 3 options (main color, bg color, orientation), but not other features, like:

- [ ] Distorted images
- [ ] Resized/stretched images
- [ ] Gradually changing colors
- [x] Round corners (like the `border-radius` CSS attribute)
- [x] Frames
- [ ] Trim out the sides!
- [ ] Use images instead of pure colors as the background/main colors!
- [ ] Add the @shoghicp avatar into the middle of it!
- [ ] Add a 2-D Perlin noise generator
- [ ] Animated images
- [ ] Other image formats
- [ ] Your own creativity!

**Comment by Bamuel** [comment]
Ideas stolen for
https://github.com/Bamuel/SOFe-Generator

**Comment by ifvictr** [comment]
Options for round corners and frames (WIP) added in fa7c3dbc42b40081c62768793d0f9ec6af9aeded. Still need some clarification on resized/stretched images, gradually changing colors, trim out the sides, animated images, and other image formats.

**Comment by ifvictr** [comment]
@SOF3 What do you mean I'm still active?

**Comment by SOF3** [comment]
You didn't resolve the issue :(

**Comment by ifvictr** [comment]
:(
